application: demoapp
instance_class: F4_1G
version: local
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"
- name: PIL
  version: "1.1.7"

builtins:
- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'demo.settings'

handlers:
- url: /static
  static_dir: static
  